## Copyright 2015 Alvaro J. Genial (http://alva.ro) -- see LICENSE.md for more.

language: haskell

ghc:
  - "7.10"
  - "7.8"
  - "7.6"
  - "7.4"

install:
  - cabal install --only-dependencies --enable-tests
  - export PATH=$HOME/.cabal/bin:$PATH
